#openvpn Access Server install
- name: Install openvpn
  apt:
    name: "{{ item }}"
    install-recommends: no
    state: present
  with_items:
    - openvpn
    - ufw
    - openssl

- name: Apply / deploy openvpn template
  template:
    src: "{{ item.src }}"
    dest: /etc/openvpn/{{ item.dest }}
  notify:
    - reload openvpn
  with_items:
    - src: server.conf.j2
      dest: server.conf
  tags:
    - configuration

- name: Install easy-rsa package
  apt: name=easy-rsa
  when: openvpn_use_system_easyrsa

#- include: configure.yml

- name: Allow masqueraded IPv4 openvpn traffic through firewall
  blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: "^# Don't delete these required lines, otherwise there will be errors$"
    marker: "# {mark} ANSIBLE MANAGED OPENVPN BLOCK"
    block: |
      # nat Table rules
      *nat
      :POSTROUTING ACCEPT [0:0]
      # Allow forwarding traffic from OpenVPN to {{ openvpn_interface }}
      -A POSTROUTING -s {{ openvpn_postroting_server_ip_subnet }} -o {{ openvpn_interface }} -j MASQUERADE
      COMMIT
  notify:
    - reload ufw
  tags:
    - ufw

- name: Allow forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
  tags:
    - network

- name: Allow ufw forwarding by default
  lineinfile:
    path: /etc/default/ufw
    regexp: "^DEFAULT_FORWARD_POLICY="
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
  notify:
    - reload ufw
  tags:
    - ufw

- name: Allow openvpn through firewall
  ufw:
    rule: allow
    proto: "{{ openvpn_proto }}"
    port: "{{ openvpn_port }}"
  notify:
    - reload ufw
  tags:
    - ufw

- include: server_keys.yml

- include: client_keys.yml
