- name: Create openvpn key directory
  file:
    path: "{{openvpn_key_dir}}"
    state: directory

- name: Copy openssl server/ca extensions
  file:
    src: "{{item}}"
    dest: "{{openvpn_key_dir}}"
  with_items:
    - openssl-server.ext
    - openssl-ca.ext

- name: Copy CA key
  copy:
    content: "{{openvpn_ca_key.key}}"
    dest: "{{openvpn_key_dir}}/ca-key.pem"
    mode: 0400
  when: openvpn_ca_key is defined

- name: Generate CA key
  command: openssl req -nodes -newkey rsa:{{openvpn_rsa_bits}} -keyout ca-key.pem -out ca-csr.pem -days 3650 -subj /CN=OpenVPN-CA-{{inventory_hostname[:53]}}/
  args:
    chdir: "{{openvpn_key_dir}}"
    creates: ca-key.pem
  when: openvpn_ca_key is not defined

- name: Sign CA key
  command: openssl x509 -req -in ca-csr.pem -out ca.crt -CAcreateserial -signkey ca-key.pem -sha256 -days 3650 -extfile openssl-ca.ext
  args:
    chdir: "{{openvpn_key_dir}}"
    creates: ca.crt
  when: openvpn_ca_key is not defined

- name: generate server key
  command: openssl req -nodes -newkey rsa:{{openvpn_rsa_bits}} -keyout server.key -out server.csr -days 3650 -subj /CN=OpenVPN-Server-{{inventory_hostname[:49]}}/
  args:
    chdir: "{{openvpn_key_dir}}"
    creates: server.key

- name: protect server key
  file:
    path: "{{openvpn_key_dir}}/server.key"
    mode: 0400

- name: sign server key
  command: openssl x509 -req -in server.csr -out server.crt -CA ca.crt -CAkey ca-key.pem -sha256 -days 3650 -CAcreateserial -extfile openssl-server.ext
  args:
    chdir: "{{openvpn_key_dir}}"
    creates: server.crt

- name: generate tls-auth key
  command: openvpn --genkey --secret ta.key
  args:
    chdir: "{{openvpn_key_dir}}"
    creates: ta.key
  when: openvpn_tls_auth_key is not defined
